from __future__ import annotations

EXACT_MATCH_SCORE = 100
MAX_NON_EXACT_SCORE = 99
MIN_POSITIVE_SCORE = 0
REASON_TOKEN_PREVIEW_LIMIT = 5

WORKFLOW_NAME_TOKEN_MATCH_SCORE = 18
WORKFLOW_BODY_TOKEN_MATCH_SCORE = 4
WORKFLOW_QUERY_PHRASE_SCORE = 25
WORKFLOW_COMMAND_TOKEN_MATCH_SCORE = 30
WORKFLOW_AUTO_SELECT_MIN_SCORE = 50
WORKFLOW_AUTO_SELECT_MARGIN = 10
WORKFLOW_HIGH_CONFIDENCE_MIN_SCORE = 80

TOOL_WORKFLOW_MATCH_SCORE = 55
TOOL_NAME_TOKEN_MATCH_SCORE = 20
TOOL_BODY_TOKEN_MATCH_SCORE = 4
TOOL_QUERY_PHRASE_SCORE = 20
TOOL_AUTO_SELECT_MIN_SCORE = TOOL_WORKFLOW_MATCH_SCORE
