from __future__ import annotations

TEXT_PREVIEW_MAX_BYTES_DEFAULT = 160
TEXT_PREVIEW_MAX_CHARS_DEFAULT = 120

TASK_RUNNER_MAX_WORKERS_DEFAULT = 4
TASK_RUNNER_MIN_WORKERS = 1
TASK_RUNNER_DURATION_DECIMALS = 3
TASK_RUNNER_POLL_TIMEOUT_SECONDS = 0.1

RAG_CHUNK_SIZE_DEFAULT = 1800
RAG_CHUNK_OVERLAP_DEFAULT = 180
RAG_EMBEDDING_DIMENSIONS_DEFAULT = 768
RAG_STANDARDIZE_RANDOM_LENGTH_DEFAULT = 8
RAG_STANDARDIZE_RANDOM_LENGTH_MIN = 5
RAG_STANDARDIZE_RANDOM_LENGTH_MAX_EXCLUSIVE = 9

RAG_RETRIEVE_TOP_K_DEFAULT = 8
RAG_RETRIEVE_MAX_CHARS_DEFAULT = 6000
RAG_DISPATCH_TOP_K_DEFAULT = 5
RAG_DISPATCH_MAX_CHARS_DEFAULT = 4000
RAG_DISPATCH_MAX_QUERIES_DEFAULT = 5
RAG_DISPATCH_JOBS_DEFAULT = TASK_RUNNER_MAX_WORKERS_DEFAULT
RAG_DISPATCH_AGGREGATE_MAX_CHARS_DEFAULT = 12000

DUCKDB_CONTEXT_MAX_CHARS_DEFAULT = RAG_DISPATCH_MAX_CHARS_DEFAULT
DUCKDB_VERIFY_MIN_RESULTS_DEFAULT = 1
DUCKDB_VERIFY_LIMIT_DEFAULT = RAG_DISPATCH_TOP_K_DEFAULT
DUCKDB_SEARCH_LIMIT_DEFAULT = 10

OUTPUT_LANGUAGE_ENGLISH_RATIO_THRESHOLD_DEFAULT = 0.62
OUTPUT_LANGUAGE_MIN_ENGLISH_WORDS_DEFAULT = 35
OUTPUT_LANGUAGE_MIN_JAPANESE_CHARS_DEFAULT = 20

FLUTTER_TIMEOUT_SECONDS_DEFAULT = 600
PROCESS_SMOKE_TIMEOUT_SECONDS = 10

SDK_ANALYSIS_MAX_FILES_DEFAULT = 200
SDK_ANALYSIS_MAX_BYTES_DEFAULT = 120_000
DISPATCHER_CANDIDATE_LIMIT_DEFAULT = 5
GITHUB_DETECT_REBASE_MAX_COMMITS_DEFAULT = 80
GITHUB_DETECT_REBASE_MAX_FILES_DEFAULT = 3
GITHUB_MESSAGE_PLAN_MAX_COMMITS_DEFAULT = 200
REVIEW_SPECIALIST_TIMEOUT_SECONDS_DEFAULT = 1800
