from __future__ import annotations

from pathlib import Path


KNOWLEDGE_SOURCE_REPO = Path("work/db/ariadne-knowledge-platform")
KNOWLEDGE_SOURCE_REPO_URL = "https://github.com/inabako/ariadne-knowledge-platform.git"
RAG_DIR_NAME = "rag"
REGISTRIES_DIR_NAME = "registries"
OPTIMIZED_CHUNKS_DIR_NAME = "optimized-chunks"
CHUNKS_DIR_NAME = "chunks"
JSONIZED_DIR_NAME = "jsonized"
NORMALIZED_DIR_NAME = "normalized"
INDEXES_DIR_NAME = "indexes"
EMBEDDINGS_DIR_NAME = "embeddings"
RETRIEVAL_DIR_NAME = "retrieval"

KNOWLEDGE_SOURCE_RAG = KNOWLEDGE_SOURCE_REPO / RAG_DIR_NAME
KNOWLEDGE_SOURCE_REGISTRIES = KNOWLEDGE_SOURCE_REPO / REGISTRIES_DIR_NAME
LEGACY_RETRIEVAL_PREFIX = f"{RAG_DIR_NAME}/{RETRIEVAL_DIR_NAME}/"

RUNTIME_RAG_ROOT = Path("runtime/rag")
RAG_INGESTION_POLICY_PATH = RUNTIME_RAG_ROOT / "policies" / "knowledge-ingestion-policy.json"
RAG_NORMALIZE_SCRIPT = RUNTIME_RAG_ROOT / "normalize_documents.py"
RAG_CHUNK_SCRIPT = RUNTIME_RAG_ROOT / "chunk_documents.py"
RAG_BUILD_INDEX_SCRIPT = RUNTIME_RAG_ROOT / "build_index.py"
RAG_EMBED_SCRIPT = RUNTIME_RAG_ROOT / "embed_chunks.py"
RAG_RETRIEVE_CONTEXT_SCRIPT = RUNTIME_RAG_ROOT / "retrieve_context.py"

# RAG JSON/JSONL artifacts are knowledge-source files; DuckDB and evidence stay under db/rag.
GENERATED_RAG = KNOWLEDGE_SOURCE_RAG

SOURCE_CORRECTIVE_ACTION_REPORTS = KNOWLEDGE_SOURCE_RAG / "corrective-action-report"
SOURCE_GITHUB_KNOWLEDGE = KNOWLEDGE_SOURCE_RAG / "github-knowledge"
SOURCE_WORKSPACE_ENVIRONMENT = KNOWLEDGE_SOURCE_RAG / "workspace-environment"

GENERATED_NORMALIZED = GENERATED_RAG / NORMALIZED_DIR_NAME
GENERATED_CHUNKS = GENERATED_RAG / CHUNKS_DIR_NAME
GENERATED_OPTIMIZED_CHUNKS = GENERATED_RAG / OPTIMIZED_CHUNKS_DIR_NAME
GENERATED_JSONIZED = GENERATED_RAG / JSONIZED_DIR_NAME
GENERATED_INDEXES = GENERATED_RAG / INDEXES_DIR_NAME
GENERATED_EMBEDDINGS = GENERATED_RAG / EMBEDDINGS_DIR_NAME
GENERATED_RETRIEVAL = GENERATED_RAG / RETRIEVAL_DIR_NAME

CHUNKS_INDEX = GENERATED_INDEXES / "chunks.jsonl"
EMBEDDINGS_INDEX = GENERATED_EMBEDDINGS / "chunks-embeddings.jsonl"
RAG_BUILD_RUN_LATEST = GENERATED_RETRIEVAL / "rag-build-run-latest.json"

DUCKDB_RAG_ROOT = Path("db/rag")
DUCKDB_DEFAULT_PATH = DUCKDB_RAG_ROOT / "ariadne-knowledge.duckdb"
DUCKDB_ERROR_LOG = DUCKDB_RAG_ROOT / "migration-errors.jsonl"
DUCKDB_EVIDENCE_DIR = DUCKDB_RAG_ROOT / "evidence"
DUCKDB_MIGRATION_EVIDENCE = DUCKDB_EVIDENCE_DIR / "migration-summary.json"
DUCKDB_REFERENCE_CHECK_OUTPUT = DUCKDB_EVIDENCE_DIR / "reference-check.json"
DUCKDB_REFERENCE_CHECK_WORK_DIR = DUCKDB_EVIDENCE_DIR
DUCKDB_INGESTION_EVIDENCE_DIR = DUCKDB_EVIDENCE_DIR / "ingestion"
DUCKDB_CONTEXT_MANIFEST = DUCKDB_EVIDENCE_DIR / "context" / "context-manifest.json"

REGISTRY_DB_PATH = Path("db/registries/registry.duckdb")
WORKFLOW_HELP_REGISTRY_FILE = "workflow_help.json"
SEARCH_TERMS_REGISTRY_FILE = "search_terms.json"
TOOL_CANDIDATES_REGISTRY_FILE = "tool_candidates.json"
HUMAN_GATES_REGISTRY_FILE = "human_gates.json"
WORKFLOW_ENVIRONMENT_PROFILES_REGISTRY_FILE = "workflow_environment_profiles.json"

LEGACY_ROOT_RAG_PREFIX = "legacy-root-rag-"

WINDOWS_FLUTTER_BIN = Path(r"C:\flutter\bin")
WINDOWS_FLUTTER_EXECUTABLES = (
    WINDOWS_FLUTTER_BIN / "flutter.bat",
    WINDOWS_FLUTTER_BIN / "flutter.cmd",
    WINDOWS_FLUTTER_BIN / "flutter.exe",
)
WINDOWS_DART_EXECUTABLES = (
    WINDOWS_FLUTTER_BIN / "dart.bat",
    WINDOWS_FLUTTER_BIN / "dart.cmd",
    WINDOWS_FLUTTER_BIN / "dart.exe",
)
WINDOWS_DEFAULT_MSYS2_ROOT = Path(r"C:\msys64")
WINDOWS_MSYS2_BASH = WINDOWS_DEFAULT_MSYS2_ROOT / "usr" / "bin" / "bash.exe"
WINDOWS_GO_EXE = Path(r"C:\Program Files\Go\bin\go.exe")

SOURCE_REPO_STANDARD_DIRS = [
    Path(RAG_DIR_NAME) / OPTIMIZED_CHUNKS_DIR_NAME,
    Path(RAG_DIR_NAME) / CHUNKS_DIR_NAME,
    Path(RAG_DIR_NAME) / JSONIZED_DIR_NAME,
    Path(RAG_DIR_NAME) / NORMALIZED_DIR_NAME,
]

LOCAL_GENERATED_STANDARD_DIRS = [
    GENERATED_OPTIMIZED_CHUNKS,
    GENERATED_CHUNKS,
    GENERATED_JSONIZED,
    GENERATED_NORMALIZED,
]
