from __future__ import annotations

SCHEMA_VERSION = "1.0"
REGISTRY_VERSION = SCHEMA_VERSION

NON_NEGATIVE_INT_DEFAULT = 0
MILLISECONDS_PER_SECOND = 1000
BYTES_PER_KIB = 1024
BYTES_PER_MIB = BYTES_PER_KIB * BYTES_PER_KIB
FILE_HASH_CHUNK_BYTES = BYTES_PER_MIB

PROBABILITY_MIN = 0.0
PROBABILITY_MAX = 1.0
PROBABILITY_DEFAULT = PROBABILITY_MIN
CONFIDENCE_DEFAULT = PROBABILITY_MAX
WEIGHT_DEFAULT = PROBABILITY_MIN

NON_NEGATIVE_FLOAT_DEFAULT = PROBABILITY_MIN
COST_AMOUNT_DEFAULT = NON_NEGATIVE_FLOAT_DEFAULT
DURATION_SECONDS_DEFAULT = NON_NEGATIVE_FLOAT_DEFAULT

NORMALIZED_SCORE_DECIMALS = 6
OPTIMIZATION_SCORE_DECIMALS = 4

GITHUB_API_TIMEOUT_SECONDS = 30

DEFAULT_RUNTIME_EVENT_MAX_MIB = 5
DEFAULT_RUNTIME_EVENT_MAX_BYTES = DEFAULT_RUNTIME_EVENT_MAX_MIB * BYTES_PER_MIB
DEFAULT_RUNTIME_EVENT_BACKUP_COUNT = 5
DEFAULT_RUNTIME_TRACE_ID_BYTES = 12
RUNTIME_EVENT_SEQUENCE_WIDTH = 5
RUNTIME_EVENT_INITIAL_SEQUENCE = NON_NEGATIVE_INT_DEFAULT
LOG_SANITIZE_STRING_MAX_CHARS_DEFAULT = 500
LOG_SANITIZE_LIST_ITEMS_MAX_DEFAULT = 20
