from __future__ import annotations

CLOSE_ARCHIVE_SAMPLE_MAX_CHARS = 4000
CLOSE_ARCHIVE_COLLECT_FILES_LIMIT = 40
CLOSE_ARCHIVE_RAG_REFERENCE_SCAN_LIMIT = 300
CLOSE_ARCHIVE_RAG_REFERENCE_TEXT_MAX_CHARS = 20_000
CLOSE_ARCHIVE_RAG_SCORE_TEXT_MAX_CHARS = 30_000
CLOSE_ARCHIVE_WORK_ID_MATCH_SCORE = 12
CLOSE_ARCHIVE_CATEGORY_SOURCE_MATCH_SCORE = 5
CLOSE_ARCHIVE_TOKEN_PATH_MATCH_SCORE = 4
CLOSE_ARCHIVE_TOKEN_TEXT_MATCH_SCORE = 2
CLOSE_ARCHIVE_RAG_DISCOVERY_SCORE_THRESHOLD = 5
CLOSE_ARCHIVE_RAG_DISCOVERY_LIMIT = 8
CLOSE_ARCHIVE_FIRST_PARAGRAPH_MAX_CHARS = 700
CLOSE_ARCHIVE_MARKDOWN_HEADINGS_LIMIT = 8
CLOSE_ARCHIVE_MARKDOWN_BULLETS_LIMIT = 12
CLOSE_ARCHIVE_MARKDOWN_BULLET_MAX_CHARS = 240
CLOSE_ARCHIVE_RAG_SUMMARY_TEXT_MAX_CHARS = 60_000
CLOSE_ARCHIVE_SOURCE_SAMPLE_MAX_CHARS = 2000
CLOSE_ARCHIVE_PRUNE_TARGETS_PREVIEW_LIMIT = 200
CLOSE_ARCHIVE_RANDOM_SUFFIX_LENGTH = 8
CLOSE_ARCHIVE_SIGNIFICANT_TOKEN_MIN_CHARS = 4
CLOSE_ARCHIVE_METADATA_SCAN_START_LINE = 1
CLOSE_ARCHIVE_METADATA_SCAN_END_LINE = 80
CLOSE_ARCHIVE_REPAIR_PERMISSION_MODE = 0o700

KNOWLEDGE_CAPTURE_TEXT_SAMPLE_MAX_CHARS = 1200
KNOWLEDGE_CAPTURE_PATH_LIST_LIMIT = 30
KNOWLEDGE_CAPTURE_DOCS_CANDIDATE_SAMPLE_MAX_CHARS = 6000

INTEGRATION_FILE_SAMPLE_LIMIT = 300
INTEGRATION_PATH_HITS_LIMIT = 20
INTEGRATION_EVIDENCE_PREVIEW_LIMIT = 200
INTEGRATION_PROBE_OUTPUT_MAX_CHARS = 500

SDK_KEYWORD_PREVIEW_LIMIT = 8
SDK_README_SAMPLE_MAX_BYTES = 4000
SDK_README_EXCERPT_MAX_CHARS = 1000

RAG_DISPATCH_COMPONENT_CANDIDATE_LIMIT = 8
CTL_WARNING_PATH_PREVIEW_LIMIT = 10
FLUTTER_COMMAND_SLUG_MAX_CHARS = 80
NOISE_REDUCTION_FINDING_PREVIEW_LIMIT = 30
SELF_IMPROVEMENT_EVENT_PREVIEW_LIMIT = 10
RUNTIME_STATUS_WORK_PREVIEW_LIMIT = 5
RUNTIME_STATUS_EVENT_READ_LIMIT = 200
RUNTIME_TRACE_EVENT_PREVIEW_LIMIT = 20

GITHUB_KNOWLEDGE_FINDING_PREVIEW_LIMIT = 10
GITHUB_KNOWLEDGE_SUBJECT_MAX_CHARS = 80
GITHUB_KNOWLEDGE_DOMAIN_SUMMARY_LIMIT = 3
GITHUB_KNOWLEDGE_PATH_SUMMARY_LIMIT = 8
GITHUB_KNOWLEDGE_CHECKLIST_PATH_LIMIT = 4
GITHUB_KNOWLEDGE_SHORT_COMMIT_CHARS = 7
GITHUB_KNOWLEDGE_COMMIT_REF_CHARS = 12
GITHUB_KNOWLEDGE_COMMAND_OUTPUT_MAX_CHARS = 4000
GITHUB_KNOWLEDGE_RAG_SOURCE_ID_RANDOM_LENGTH = 6
GITHUB_KNOWLEDGE_PATH_AFFINITY_EXACT_PATH_SCORE = 6
GITHUB_KNOWLEDGE_PATH_AFFINITY_DIRECTORY_SCORE = 4
GITHUB_KNOWLEDGE_PATH_AFFINITY_DOMAIN_SCORE = 3
GITHUB_KNOWLEDGE_PATH_AFFINITY_ROOT_SCORE = 2
GITHUB_KNOWLEDGE_SEMANTIC_SUBJECT_BONUS = 2
GITHUB_KNOWLEDGE_RELATED_SCORE_DEFAULT = 0
GITHUB_KNOWLEDGE_MIN_POSITIVE_RELATED_SCORE = 0
GITHUB_KNOWLEDGE_HISTORY_FILE_PATH_MIN = 1
GITHUB_KNOWLEDGE_HISTORY_FILE_PATH_MAX = 3
GITHUB_KNOWLEDGE_GIT_LOG_SAMPLE_COMMITS = 20
GITHUB_KNOWLEDGE_GIT_LOG_SAMPLE_COMMAND = f'git log --format="%H %s" --max-count={GITHUB_KNOWLEDGE_GIT_LOG_SAMPLE_COMMITS}'
GITHUB_KNOWLEDGE_ORDER_FALLBACK = 10**9

REQUIREMENTS_COMPARISON_PREVIEW_LINES = 40
