from __future__ import annotations

EMPTY_QUERY_SCORE = 1
MIN_SEARCH_MATCH_SCORE = 0
BLOB_ALL_TERMS_BASE_SCORE = 40
BLOB_TERM_MATCH_SCORE = 10
EXPLICIT_TERM_EXACT_MATCH_SCORE = 120
EXPLICIT_TERM_PARTIAL_MATCH_SCORE = 90
EXPLICIT_TERM_ALL_TERMS_SCORE = 75
EXPLICIT_TERM_SINGLE_MATCH_SCORE = 25
