from __future__ import annotations

from runtime.constants.runtime_values import (
    CONFIDENCE_DEFAULT,
    NON_NEGATIVE_INT_DEFAULT,
    NORMALIZED_SCORE_DECIMALS,
    PROBABILITY_DEFAULT,
    PROBABILITY_MAX,
    PROBABILITY_MIN,
    WEIGHT_DEFAULT,
)


DEFAULT_EXPECTATION_CONFIDENCE = CONFIDENCE_DEFAULT
DEFAULT_USAGE_CONTEXT_CONFIDENCE = CONFIDENCE_DEFAULT
DEFAULT_EVALUATION_CONFIDENCE = CONFIDENCE_DEFAULT
DEFAULT_CRITICAL_MINIMUM_PROBABILITY = PROBABILITY_MAX
DEFAULT_EXPECTATION_PROBABILITY = PROBABILITY_DEFAULT
DEFAULT_AXIS_SCORE = PROBABILITY_DEFAULT
DEFAULT_EXPECTATION_WEIGHT = WEIGHT_DEFAULT
DEFAULT_SAMPLE_EXPECTATION_WEIGHT = PROBABILITY_MAX
DEFAULT_AGENT_EXTRACTION_CONFIDENCE = 0.6
DEFAULT_LIGHT_EXTRACTION_CONFIDENCE = 0.7
DEFAULT_FIXED_UI_CONFIDENCE = 0.65
DEFAULT_FALLBACK_EXPECTATION_CONFIDENCE = 0.5

SCORE_MIN = PROBABILITY_MIN
SCORE_MAX = PROBABILITY_MAX
SCORE_ROUND_DECIMALS = NORMALIZED_SCORE_DECIMALS
COUNT_DEFAULT = NON_NEGATIVE_INT_DEFAULT
COUNT_INCREMENT = 1
SEQUENCE_START = 1

MAJOR_VIOLATION_THRESHOLD = 0.5
MINOR_VIOLATION_THRESHOLD = 0.8
AMBIGUOUS_PROBABILITY_LOWER = 0.4
AMBIGUOUS_PROBABILITY_UPPER = 0.6
LOW_CONFIDENCE_THRESHOLD = 0.5
POSITIVE_SURPRISE_THRESHOLD = 0.95

TRADEOFF_GAIN_THRESHOLD = 0.8
TRADEOFF_LOSS_THRESHOLD = 0.6
COMPARISON_RECOMMENDATION_LIMIT = 1
COMPARISON_KEY_POINT_LIMIT = 3
EXPECTATION_AGENT_ID_WIDTH = 3
INTERACTION_CONTRACT_ID_WIDTH = 3
DEFAULT_USAGE_CONTEXT_ID = "CONTEXT-001"
USAGE_CONTEXT_GOAL_MAX_CHARS = 160
WEIGHT_CHANGE_FIELD_COUNT = 3

EXPECTATION_VIOLATION_SEVERITY_ORDER = {
    "critical": 0,
    "major": 1,
    "minor": 2,
    "ambiguous": 3,
    "unverified": 4,
    "positive-surprise": 5,
}
EXPECTATION_VIOLATION_SEVERITY_ORDER_DEFAULT = 99

WIREFRAME_WIDTH = 960
WIREFRAME_HEIGHT = 540
WIREFRAME_HEADER_X = 80
WIREFRAME_HEADER_Y = 64
WIREFRAME_HEADER_WIDTH = 800
WIREFRAME_HEADER_HEIGHT = 72
WIREFRAME_LEFT_PANEL_X = 80
WIREFRAME_PANEL_Y = 168
WIREFRAME_LEFT_PANEL_WIDTH = 320
WIREFRAME_PANEL_HEIGHT = 260
WIREFRAME_RIGHT_PANEL_X = 432
WIREFRAME_RIGHT_PANEL_WIDTH = 448
WIREFRAME_TITLE_X = 112
WIREFRAME_TITLE_Y = 108
WIREFRAME_TITLE_FONT_SIZE = 24
WIREFRAME_LABEL_X = 112
WIREFRAME_LABEL_Y = 220
WIREFRAME_RIGHT_LABEL_X = 464
WIREFRAME_LABEL_FONT_SIZE = 18

SAMPLE_LOW_EXPECTATION_PROBABILITY = 0.2
SAMPLE_HIGH_EVALUATION_CONFIDENCE = POSITIVE_SURPRISE_THRESHOLD
SAMPLE_STRONG_EVALUATION_CONFIDENCE = 0.9

SAMPLE_MULTI_AXIS_DESIGN_A_SCORES = {
    "expectation_satisfaction": SAMPLE_LOW_EXPECTATION_PROBABILITY,
    "usability": 0.55,
    "product_identity": 0.45,
    "delight": 0.4,
    "accessibility": TRADEOFF_LOSS_THRESHOLD,
    "implementation_cost": 0.85,
    "maintenance_cost": 0.75,
    "technical_feasibility": TRADEOFF_GAIN_THRESHOLD,
}
SAMPLE_MULTI_AXIS_DESIGN_B_SCORES = {
    "expectation_satisfaction": SCORE_MAX,
    "usability": 0.85,
    "product_identity": 0.75,
    "delight": DEFAULT_LIGHT_EXTRACTION_CONFIDENCE,
    "accessibility": TRADEOFF_GAIN_THRESHOLD,
    "implementation_cost": DEFAULT_FIXED_UI_CONFIDENCE,
    "maintenance_cost": DEFAULT_LIGHT_EXTRACTION_CONFIDENCE,
    "technical_feasibility": 0.75,
}
