from __future__ import annotations

from runtime.constants.runtime_values import OPTIMIZATION_SCORE_DECIMALS, PROBABILITY_MAX, PROBABILITY_MIN


SCORE_MIN = PROBABILITY_MIN
SCORE_MAX = PROBABILITY_MAX
SCORE_DEFAULT = SCORE_MIN
EMBEDDING_VALUE_DEFAULT = SCORE_DEFAULT
AVERAGE_OPTIMIZATION_SCORE_DEFAULT = SCORE_DEFAULT
SPARSE_EMBEDDING_HASH_BYTES = 8
SPARSE_EMBEDDING_VALUE_DECIMALS = 8

KEYWORD_CONTAINS_BONUS = 2.0
HEADING_MATCH_BONUS = 3.0
SEMANTIC_SCORE_SCALE = 100.0
HYBRID_SEMANTIC_WEIGHT = 35.0
TEXT_MATCH_SCORE_DECIMALS = OPTIMIZATION_SCORE_DECIMALS

LONG_TEXT_BLOCK_CHARS = 700
FALLBACK_SELECTED_UNIT_COUNT = 3
TRUNCATION_RESERVED_CHARS = 20
TOKEN_ESTIMATE_CHARS_PER_TOKEN = 2.5
MIN_CONTEXT_REMAINING_CHARS = 200
MIN_PER_CHUNK_CONTEXT_BUDGET = 300
SECTION_SEPARATOR_CHARS = 2

SEMANTIC_EMPTY_SCORE = SCORE_MIN
SEMANTIC_HEADING_ONLY_SCORE = 0.25
SEMANTIC_SHORT_TEXT_CHARS = 40
SEMANTIC_SHORT_TEXT_SCORE = 0.45
SEMANTIC_BASE_SCORE = 0.62
SEMANTIC_LENGTH_BONUS_CAP = 0.28
SEMANTIC_LENGTH_BONUS_DIVISOR = 1200
SEMANTIC_SENTENCE_BONUS_CAP = 0.10
SEMANTIC_SENTENCE_MARKER_WEIGHT = 0.02

RETRIEVAL_DECORATION_ONLY_SCORE = 0.1
RETRIEVAL_BASE_SCORE = 0.35
RETRIEVAL_UNIQUE_TERM_BONUS_CAP = 0.30
RETRIEVAL_UNIQUE_TERM_DIVISOR = 80
RETRIEVAL_HEADING_BONUS = 0.15
RETRIEVAL_TAG_BONUS = 0.15

SOURCE_RELIABILITY_BASE_SCORE = 0.50
SOURCE_RELIABILITY_HIGH_TRUST_BONUS = 0.30
SOURCE_RELIABILITY_MEDIUM_TRUST_BONUS = 0.15
SOURCE_RELIABILITY_LOW_TRUST_PENALTY = 0.15
SOURCE_RELIABILITY_APPROVED_STATUS_BONUS = 0.20
SOURCE_RELIABILITY_DRAFT_STATUS_BONUS = 0.15
SOURCE_RELIABILITY_SOURCES_BONUS = 0.10
SOURCE_RELIABILITY_COMMIT_BONUS = 0.10
TRACEABILITY_PRESENT_FIELD_DIVISOR = 6

CONTEXT_INDEPENDENCE_AMBIGUITY_CAP = 0.75
CONTEXT_INDEPENDENCE_AMBIGUITY_WEIGHT = 0.18
NOISE_PATTERN_PENALTY_CAP = 0.35
NOISE_PATTERN_PENALTY_WEIGHT = 0.12
NOISE_REPETITION_PENALTY_CAP = 0.35
NOISE_REPETITION_PENALTY_WEIGHT = 0.8
NOISE_DECORATION_PENALTY = 0.45
DUPLICATE_CONTENT_PENALTY = SCORE_MAX
AMBIGUITY_PENALTY_CAP = 0.8
AMBIGUITY_PENALTY_WEIGHT = 0.18
OVERSIZE_TEXT_CHARS = 2400
FRAGMENT_HEADING_ONLY_PENALTY = 0.9
FRAGMENT_CODE_BLOCK_PENALTY = 0.65
FRAGMENT_SHORT_TEXT_CHARS = 25
FRAGMENT_SHORT_TEXT_PENALTY = 0.75
FRAGMENT_INCOMPLETE_SENTENCE_PENALTY = 0.45
CONFLICT_PENALTY_CAP = 0.8
CONFLICT_TERM_WEIGHT = 0.20
DEFAULT_ACCEPT_THRESHOLD = 0.80
DEFAULT_REWRITE_THRESHOLD = 0.55
ACCEPT_WITH_NOISE_REWRITE_THRESHOLD = 0.12

DUCKDB_FRESHNESS_PRESENT_SCORE = SCORE_MAX
DUCKDB_FRESHNESS_MISSING_SCORE = 0.5
DUCKDB_DUPLICATION_SCORE_BASE = SCORE_MAX
